### ISSUE TITLE
AssertionError: No records found!

### ISSUE THREAD

**Issue by guzhiqian** [smangham/bindata#2]
There is a issue that show 'AssertionError: No records found!' when I execute   tfpy.TransferFunction.run(). , in line 589. 
How to solve the issue.

**Comment by smangham** [comment]
That error arises when no photons meet your filter criteria; i.e. you tried filtering for a line number that isn't valid, or for a delay range that no photons fall into.
This repository is now deprecated. An updated version of the code in it is now merged into the `agnwinds:python` repository, and I'm just sorting out a worked example for how to use it. It's currently available here: https://github.com/smangham/reverb_example
